service: ahv-council-mailer

provider:
  name: aws
  runtime: nodejs4.3

  stage: dev
  region: us-west-2
  environment:
    SLACK_WEBHOOK_URL: ${file(env.dev.yml):slack_webhook_url}
    SLACK_VERIFICATION_TOKEN: ${file(env.dev.yml):slack_verification_token}
    SEND_FROM: ${file(env.dev.yml):send_from}
    SEND_TO: ${file(env.dev.yml):send_to}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  createLetter:
    handler: handler.createLetter
    events:
      - http:
          path: submit
          method: post
          private: false

  approveLetter:
    handler: handler.approveLetter
    events:
      - http:
          path: approve
          method: post
          private: false
