service: ahv-council-mailer

provider:
  name: aws
  runtime: nodejs4.3

  stage: dev
  region: us-west-2
  environment: ${file(env.dev.yml)}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  createLetter:
    handler: handler.createLetter
    events:
      - http:
          path: submit
          method: post
          private: false
          cors: true

  approveLetter:
    handler: handler.approveLetter
    events:
      - http:
          path: approve
          method: post
          private: false
