service: ahv-council-mailer

provider:
  name: aws
  runtime: nodejs4.3

  stage: dev
  region: us-west-2

  environment: ${file(env.dev.yml)}

functions:
  createLetter:
    handler: handler.createLetter
    events:
      - http:
          path: submit
          method: post
          private: false

  approveLetter:
    handler: handler.approveLetter
    events:
      - http:
          path: approve
          method: post
          private: false
